[package]
name = "prooheckcp/roactmotion"
description = "A simple library inspired by Framer Motion and Flipper that allows you to easily animate Roact UI. It supports events such as hovering and pressing on buttons. Developed by @prooheckcp"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["ReplicatedStorage", "default.project.json", "wally.toml"]