[package]
name = "prooheckcp/roactmotion"
description = "A simple library inspired by Framer Motion and Flipper that allows you to easily animate Roact UI. It supports events such as hovering and pressing on buttons. Developed by @prooheckcp. You can read it's documentation at: https://github.com/prooheckcp/RoactMotion"
version = "0.1.9"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Prooheckcp"]
exclude = ["**"]
include = [
    "default.project.json", 
    "src", 
    "wally.lock", 
    "wally.toml",
    "src/*"
]